### PR TITLE
Add flexiramp

### PR DESCRIPTION
**Pull request by oyurdakul**
Incorporated flexiramp products into the package

### CODE REVIEW

**Comment by iSoron** [comment]
Hi Ogun, thank you very much for the pull request! Sorry for the delay, I was away from the project for a while.

I have reformatted the source code according to our code conventions (using `make format`) and merged the latest changes from the `dev` branch into this PR. To fetch these changes to your machine, you can use `git pull`. Please let me know if you have any questions.

Everything looks good overall, but some of our automated tests are failing. [You can see the failed test results on GitHub Actions](https://github.com/ANL-CEEESA/UnitCommitment.jl/runs/5383137879?check_suite_focus=true). Could you try to fix these issues? After you push new changes to this PR, GitHub should automatically run the tests again.

**Comment by iSoron** [comment]
@oyurdakul It seems like some checks are still failing. Please let me know if you need help with these. I am currently waiting until this PR is done to merge the branch `feature/reserves`, which adds zonal reserves to the package.

**Comment by iSoron** [comment]
@oyurdakul If all the lint actions pass in your local machine but not on GitHub Actions, perhaps you are using a different version of the `JuliaFormatter` package. For this project we currently use version `0.14.4`. You can install it as follows:

```julia
using Pkg
Pkg.add(PackageSpec(name="JuliaFormatter", version="0.14.4"))
```

You can also format the source code by running `make format`.

**Comment by oyurdakul** [comment]
@iSoron Thanks for your help. The lint action fails also on my local machine. In fact, I created a new lint action that formats only the benchmark folder, and it fails as well although I did not modify it at all. I will try to sort it out asap.

**Comment by oyurdakul** [comment]
@iSoron Could you please approve the runs [Add flexiramp](https://github.com/ANL-CEEESA/UnitCommitment.jl/actions/runs/2077535329) and [Add flexiramp](https://github.com/ANL-CEEESA/UnitCommitment.jl/actions/runs/2077535328) triggered by my latest commit [b4bc50c](https://github.com/ANL-CEEESA/UnitCommitment.jl/pull/21/commits/b4bc50c865e236c46732c601ff0ec07c3e6f0931)? They should be working now.

**Comment by iSoron** [comment]
@oyurdakul Approved. I have also changed the repository settings so that approval is only required for accounts that are new to GitHub, not all first-time contributors to the project.

**Comment by oyurdakul** [comment]
Thanks @iSoron! All checks seem to have passed, let me know if there is anything else you need from my end.

**Comment by iSoron** [comment]
Thanks for the PR, @oyurdakul! I have merged it with a few minor edits. I've also added your name to the list of authors.

**Pull request merged**
