### PR TITLE
LMP Methods & Profiled Units

### PR DESCRIPTION
**Pull request by hejun0524**
1. LMP and AELMP methods:
   - `src/lmp`: directory that contains all source codes under two sub-directories `lmp` and `aelmp`. Each sub-directory contains `structs.jl` and `compute.jl` which corresponds to each LMP method struct and each `compute_lmp` function, respectively.
   - `src/lmp/structs.jl`: abstract `PricingMethod` type to be inherited for specific LMP method.
2. Tests:
   - `lmp/lmp_test.jl`: lmp testcase using 4 simple examples from the slides.
   - `lmp/aelmp_test.jl`: aelmp testcase using aelmp_simple.
   - `test/runtests.jl`: registered the two pricing tests defined above.
   - `test/Project.toml`: added `HiGHS` which is used in the tests.
   - `fixtures`: 5 simple testcases are added.
3. Docs:
   - `docs/src/usage.md`: added docs for computing LMPs and AELMPs.
4. The `UnitCommitment.jl` file:
   - included all structs, compute methods (the 5 files defined in Bullet Point 1 above).

### CODE REVIEW

**Comment by iSoron** [comment]
Hi @hejun0524, thanks for the PR. I made several minor changes. Could you please have a look and confirm that everything looks fine?

Regarding the limitations of the AELMP method:

1. Before, the docs mentioned that minimum up/down must be zero, but, in our data format, the "unrestricted" amount would actually be 1. That is, the unit can turn off at the next time period. I've changed it in the docs, but not in the code.
2. Regarding unsupported time-varying parameters, it would be nice to check and raise an error if time-varying values are detected.
3. The last limitation was unclear to me. I've rewritten it as "AELMPs are only calculated for the first time period if offline participation is not allowed". Is that what you meant? If not, feel free to revise.

**Comment by hejun0524** [comment]
Hi @iSoron, I made some modifications on the doc and aelmp code. 

1. Right now, the code checks if the min up/down time are > 1, if the initial status is negative, if the initial power is 0, and if the array of start up costs (in the StartupCategories list) has length > 1. If any of these happens, it throws the error instead of automatically changing the instance. 
 - I moved these codes from the `_modify_instance!` function to `_aelmp_check_parameters` function so that the checking process happens before modifying the data.

2. I changed the warning section of AELMP in the doc. It includes what I mentioned above, and in addition, how the model determines if an asset is offline (the change is also made in the code).
 - In the earlier commitment an asset is offline if it is OFF at t=1.
 - Now it is offline if it is NEVER on throughout t = 1 to T. I read the paper but it gave the math derivation of "single-period AELMP" only, and according to their numerical example, it did not say but looked like the author was treating a generator to be offline if it has never been on. 

3. I did some simple tests by feeding in some "invalid" data and all of them threw out the errors as expected, and the modification still passed all the testcases I previously wrote.

**Comment by hejun0524** [comment]
I noticed something has been changed in the outer layer. A UC Scenario struct has been added and all the tests failed in this PR check.

**Comment by hejun0524** [comment]
`src/UnitCommitment.jl`
 - Added the source code file for profiled units (`src/model/formulations/base/punit.jl`).

`src/instance/migrate.jl`
 - Added migration to 0.4.

`src/instance/read.jl`
 - Changed the generator units part to identify the `Type` attribute and include profiled units.

`src/instance/structs.jl`
 - Added the structs for profiled units, changed the bus and scenario to include profiled units.

`src/model/build.jl`
 - Added a for-loop to build the optimization model of the profiled units part, calls the function defined in `punit.jl` file below.

`src/model/formulations/base/punit.jl`
- Created this file to append a profiled unit to the optimization model (decision variables, constraints and objective function).

`src/solution/solution.jl`
- Wrapped the thermal units part with an if-condition that checks if the model has any thermal units first.
- Added the profiled units part.

~~`test/instance/migrate_test.jl`~~
- ~~Added test case for migration to 0.4.~~
- ~~Note that in Fixture, a file with name `ucjl-0.4.json.gz` is added.~~

`test/instance/read_test.jl`
- Added test case for reading. 
- ~~It seems that case14.json.gz is solved somewhere else and if the profiled units are added those results may change.
- Instead I created a new file named `case14-profiled.json.gz`. I added two more generators into the file (and I think ucjl-0.3.json.gz and case14.json.gz are related, if so, then ucjl-0.4 and case14-profiled should also be related.)~~
- The test case ~~uses exactly the same code as the first `read_benchmark` test case, with an additional~~ checks on the number of profiled units (`==2`) and an additional check on whether the code reads both profiled units correctly.

**Comment by iSoron** [comment]
Thanks for the changes, Jun. I think it's almost ready to merge, but we also need to modify the following files to take profiled units into account. Please let me know if you have any questions.

- [ ] `src/transform/randomize/XavQiuAhm2021.jl` - the function `_randomize_costs` should also randomize profiled unit costs
- [ ] `src/validation/validate.jl` - we should check that profiled units are producing power within the limits
- [ ] `src/transform/initcond.jl` - we should add the profiled units to the auxiliary optimization problem we solve to find initial conditions, otherwise it might be infeasible

**Pull request merged**
