### PR TITLE
Feature/fix vars

### PR DESCRIPTION
**Pull request by akazachk**
Introduce `fix_vars_via_constraint` as requested here: https://github.com/ANL-CEEESA/UnitCommitment.jl/pull/13#issuecomment-885957748

### CODE REVIEW

**Comment by iSoron** [comment]
Hi Alex, thank you for the PR! If I understand correctly, we are introducing two changes here:

1. For must-run units, we now let the user decide whether to enforce the must-run constraints by: (i) replacing `is_on`, `switch_on` and `switch_off` by constants; or (ii) using `JuMP.fix`.
2. We now enforce additional constraints on `is_on`, `switch_on` and `switch_off`, based on the initial condition of the generator.

For the first change, I no longer think that replacing `is_on`, `switch_on` and `switch_off` by constants is a good idea. It makes the model harder to query, debug and modify, as you mentioned before. I now agree with you, and I suggest that we completely remove this option. An alternative method, which I mentioned in #13, is to enforce must-run constraints by actually adding new constraints to the model (i.e. `@constraint(model, is_on[g.name, t] >= 1)`. I would like to benchmark this against `JuMP.fix`. If the two methods have same performance, I would prefer having only the constraint method, to keep the code base simple. If `JuMP.fix` is much faster, then we can drop the constraint method.

For the second change (enforcing additional constraints based on initial condition), it's not clear to me that these constraints would have any impact on the performance; it looks like something that the pre-processor would easily figure out. Unless we have benchmarks showing that they are helpful, I suggest not including them.

**Comment by akazachk** [comment]
> Hi Alex, thank you for the PR! If I understand correctly, we are introducing two changes here:
> 
> 1. For must-run units, we now let the user decide whether to enforce the must-run constraints by: (i) replacing `is_on`, `switch_on` and `switch_off` by constants; or (ii) using `JuMP.fix`.
> 2. We now enforce additional constraints on `is_on`, `switch_on` and `switch_off`, based on the initial condition of the generator.
> 
> For the first change, I no longer think that replacing `is_on`, `switch_on` and `switch_off` by constants is a good idea. It makes the model harder to query, debug and modify, as you mentioned before. I now agree with you, and I suggest that we completely remove this option.

Sure, we can do that in a future PR, by replacing the "constant" here with @constraint. This PR is just introducing the option, and I did not want to combine both changes.

> An alternative method, which I mentioned in #13, is to enforce must-run constraints by actually adding new constraints to the model (i.e. `@constraint(model, is_on[g.name, t] >= 1)`. I would like to benchmark this against `JuMP.fix`. If the two methods have same performance, I would prefer having only the constraint method, to keep the code base simple. If `JuMP.fix` is much faster, then we can drop the constraint method.

I support that. I suggest we merge into the `dev` branch now, and decide which is better later, since we need to make the constant -> constraint changes too.

> 
> For the second change (enforcing additional constraints based on initial condition), it's not clear to me that these constraints would have any impact on the performance; it looks like something that the pre-processor would easily figure out. Unless we have benchmarks showing that they are helpful, I suggest not including them.

Hmm, but some instance-specific preprocessing might make sense. I am not sure we should rely on the solver, given that we actually know things about the model. Moreover, some preprocessors are worse than others (e.g., Cbc's).

Maybe we could move that part out to a new "preprocess" file?

**Comment by iSoron** [comment]
> I suggest we merge into the dev branch now, and decide which is better later, since we need to make the constant -> constraint changes too.

I would like to avoid introducing `fix_vars_via_constraint` if we are going to remove it a few commits later, especially since it adds quite some code complexity. We can leave this PR on hold until we run benchmarks to figure out the performance impact of using `@constraint(model, x <= 0)` versus `fix(x, 0)`.

> Hmm, but some instance-specific preprocessing might make sense. I am not sure we should rely on the solver, given that we actually know things about the model. Moreover, some preprocessors are worse than others (e.g., Cbc's).

If we can show that certain constraints help Cbc, even if they don't help more advanced solvers, we can include them.

**Comment by akazachk** [comment]
> > I suggest we merge into the dev branch now, and decide which is better later, since we need to make the constant -> constraint changes too.
> 
> I would like to avoid introducing `fix_vars_via_constraint` if we are going to remove it a few commits later, especially since it adds quite some code complexity. We can leave this PR on hold until we run benchmarks to figure out the performance impact of using `@constraint(model, x <= 0)` versus `fix(x, 0)`.
> 
> > Hmm, but some instance-specific preprocessing might make sense. I am not sure we should rely on the solver, given that we actually know things about the model. Moreover, some preprocessors are worse than others (e.g., Cbc's).
> 
> If we can show that certain constraints help Cbc, even if they don't help more advanced solvers, we can include them.

@iSoron, sure, that makes sense. I will run some comparisons with Cbc using the `@constraint` and `fix` options, and with/without the extra preprocessing.

Is there an option for branches that introduce "improving features" to automatically be benchmarked against the `dev` branch when the pull request is made?

**Pull request closed without merging**
